-- 012_add_idempotency_key_to_orders.sql
-- Add idempotency_key column to prevent duplicate orders

-- Add idempotency_key column (nullable for existing orders, unique for new ones)
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS idempotency_key TEXT;

-- Create unique index for fast lookups
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency_key 
ON public.orders(idempotency_key) 
WHERE idempotency_key IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN public.orders.idempotency_key IS 
'Unique key generated by client to prevent duplicate orders from retries or double-clicks. If an order with this key already exists, return that order instead of creating a new one.';









